Repository gloddy-dev/notification-server, pull requests merged in 2023-11, with the labels that each got.

#3 [Infra, Feat]: AWS SQS handler 구현 및 Application 포트와 연동 (Apply, Group)
  bootstrap/src/main/resources/application.yml
  in-adapter-messaging/build.gradle.kts
  in-adapter-messaging/src/main/kotlin/gloddy/.gitkeep
  in-adapter-messaging/src/main/kotlin/gloddy/handler/InPayloadHandler.kt
  in-adapter-messaging/src/main/kotlin/gloddy/handler/mapper/ApplicationEventMapper.kt
  in-adapter-messaging/src/main/kotlin/gloddy/payload/apply/ApplyPayload.kt
  in-adapter-messaging/src/main/kotlin/gloddy/payload/apply/ApplyPayloadType.kt
  in-adapter-messaging/src/main/kotlin/gloddy/payload/group/GroupMemberPayload.kt
  in-adapter-messaging/src/main/kotlin/gloddy/payload/group/GroupMemberPayloadType.kt
  in-adapter-messaging/src/main/kotlin/gloddy/sqs/listener/SqsHandler.kt
  in-adapter-messaging/src/main/kotlin/gloddy/sqs/util/MessageParser.kt
  in-adapter-messaging/src/main/resources/application-message.yml
  in-adapter-messaging/src/main/resources/application.yml
  notification-in-adapter-api/src/main/kotlin/gloddy/health/HealthCheckController.kt
Labels: feature, infra

#4 [FEAT]: Cors 설정 추가
  notification-in-adapter-api/src/main/kotlin/gloddy/config/WebConfig.kt
Labels: feature, chore

#12 [FIX]: Apply Event 타입에 따라 TargetUserId 반환하는 메소드 구현
  notification-application/src/main/kotlin/gloddy/notification/service/ApplyNotificationCreateService.kt
  notification-domain/src/main/kotlin/gloddy/notification/NotificationType.kt
Labels: fix

#16 [CHORE]: 프런트 개발 서버 CORS 설정
  notification-in-adapter-api/src/main/kotlin/gloddy/config/WebConfig.kt
Labels: chore

#18 [REFACTOR]: 푸시 이벤트 발행 시 Notification 도메인 객체 넘겨주도록 리팩토링
  notification-application/src/main/kotlin/gloddy/notification/event/NotificationCreateEvent.kt
  notification-application/src/main/kotlin/gloddy/notification/event/NotificationEvent.kt
  notification-application/src/main/kotlin/gloddy/notification/event/NotificationEventPublisher.kt
  notification-application/src/main/kotlin/gloddy/notification/event/NotificationPushEvent.kt
  notification-application/src/main/kotlin/gloddy/notification/service/ApplyNotificationCreateService.kt
  notification-application/src/main/kotlin/gloddy/notification/service/GroupNotificationCreateService.kt
  notification-domain/src/main/kotlin/gloddy/notification/NotificationType.kt
  out-internal-api/src/main/kotlin/gloddy/.gitkeep
  out-internal-api/src/main/kotlin/gloddy/openFeign/OpenFeignConfig.kt
  push/src/main/kotlin/gloddy/NotificationPushController.kt
  push/src/main/kotlin/gloddy/NotificationPushService.kt
  push/src/main/kotlin/gloddy/PushClient.kt
  push/src/main/kotlin/gloddy/PushData.kt
  push/src/main/kotlin/gloddy/command/GroupingPushCommand.kt
  push/src/main/kotlin/gloddy/command/GroupingPushType.kt
  push/src/main/kotlin/gloddy/command/PushCommand.kt
  push/src/main/kotlin/gloddy/command/PushCommandMapper.kt
  push/src/main/kotlin/gloddy/event/NotificationEventListener.kt
Labels: refactor
